### ISSUE TITLE
package:github is reported as Web-only

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dev#2926]
https://pub.dev/packages/github has both web _and_ io support. See: https://github.com/SpinlockLabs/github.dart/tree/master/lib.

cc @robrbecker, the author

**Comment by robrbecker** [comment]
I've noticed this too and wanted to use conditional import/exports with one entry point to work around it. Looks like someone coincidentally just yesterday put up a PR to do just that https://github.com/SpinlockLabs/github.dart/pull/183

In general, I don't love the split between io and html. Maybe this will make things easier to work everywhere https://github.com/dart-lang/sdk/issues/35969

**Comment by jonasfj** [comment]
Support for conditional imports in package analysis is still missing https://github.com/dart-lang/pub-dev/issues/2763.

But I'm sure we'll get that sorted out at some point.

**Comment by jonasfj** [comment]
Note: for http, just use `package:http/http.dart` it does conditional imports on its own... So you'll only need to do the env variable thing by importing a different file.

**Comment by robrbecker** [comment]
@jonasfj I've started refactoring to a single cross platform entry point. Will this layout work better with detection in pub? https://github.com/SpinlockLabs/github.dart/tree/dev

**Comment by jonasfj** [comment]
@robrbecker, not yet, but I strongly suspect we'll eventually need to support conditional imports in the platform detection logic -- which is going to be refactored soon, anyways.

**Comment by robrbecker** [comment]
I've released version 6 which seems to detect correctly, even with conditional imports.
![image](https://user-images.githubusercontent.com/314858/68549247-77133c00-03b3-11ea-9069-80bf8b1341f5.png)

Looks like you can close this issue.

**Comment by jonasfj** [comment]
Ah, it doesn't detect anything when you use an empty stub as the default case... Or so I think..

We still don't have proper support for conditional imports in pana. But we are look at this soon.
