### ISSUE TITLE
Possible feature: Add accessibility score to PubDev score

### ISSUE THREAD

**Issue by nilsreichardt** [dart-lang/pub-dev#3848]
## Problem
Many packages have no accessibility support (Text scaling, screen reader, etc.), which is a big problem for me as an app developer. It's my responsibility that our app has accessibility support. There are no quick indicators to know if a package has accessibility support...

Especially the AppStore team pays a lot of attention to accessibility (when it comes to featuring).

#### Example of problems
* At the moment [flutter_markdown](https://pub.dev/packages/flutter_markdown) doesn't scale text size, if users change the system font size (https://github.com/flutter/flutter_markdown/issues/242)
* Two weeks ago I added the screen reader support in [qr.flutter](https://pub.dev/packages/qr_flutter) (for `QrImage`). Screen readers simply ignored the QR Code (very critical). PR: https://github.com/lukef/qr.flutter/pull/93; `QrPainter` still haven't screen reader support (https://github.com/lukef/qr.flutter/issues/101)
* [sliding_up_panel](https://pub.dev/packages/sliding_up_panel) blocks the whole app for screen reader, if backdropEnabled is true! (https://github.com/akshathjain/sliding_up_panel/issues/168)
* Flares [(flare_flutter)](https://pub.dev/packages/flare_flutter) can't be focused by screen readers (https://github.com/2d-inc/Flare-Flutter/issues/266)

## Idea
An idea would be a accessibility score to get maintainers more motivated. But the main point of the accessibility score is, that **developers can see directly whether the package has accessibility support.** I would directly see that [flutter_markdown](https://pub.dev/packages/flutter_markdown) doesn't scale font size --> no accessibility support.

Are there any good solutions to integrate this? Maybe you could scan the package example app 🤷‍♂️

**Comment by timsneath** [comment]
I love the idea, and in principle we'd eagerly adopt something like this. 

The challenge is execution, obviously -- packages are scanned through an automated tool, [pana](https://github.com/dart-lang/pana/), and we'd need to identify some checks that would support this. Would appreciate ideas from you or others about rules that we could apply here. 

Separately, I notice that the [Flutter Favorite](https://flutter.dev/docs/development/packages-and-plugins/favorites) program doesn't yet include accessibility as an explicit part of its criteria (although it does mention 'usability'). Since this includes a manual review step, it would be viable to include some kind of accessibility test in this award moving forward. I'll raise that with the team for consideration.

**Comment by sigurdm** [comment]
This is a great idea for the flutter-favorite program. 
This doesn't really belong on the pub-dev issue tracker.
Closing this here.
@timsneath do you want to open this in the flutter issue tracker?

**Comment by timsneath** [comment]
To my sorrow, this issue has bounced around a couple of trackers but not been picked up by anyone :( 

Rather than bounce it around again, I'm going to reopen it here. The Flutter Favorites program has been on a short hiatus due to team changes (folk on leave, transitions), but I think we should just agree that this should be factored into their reviews moving forward. @johnpryan for visibility.

**Comment by sigurdm** [comment]
So if we believe accessibility can be checked automatically where do we fit these in?

I think the best way be to create a number of lints that warn about inaccessible usage of API (forgetting to fill in `onPressed` etc. and adding these lints to the flutter default lints).

Then any violated lints would show up in the pana results, and result in a lower score.

Or are there checks that are so special they have to live in pana?

**Comment by nilsreichardt** [comment]
> Or are there checks that are so special they have to live in pana?

If we want to fully cover accessibly, we can't do it automatically. However, I think it's enough for the beginning to just have some lints as you said which effects the pub dev score. I think have some lints shouldn't be that hard, like have always a `Semantics.button = true` for `GestureDector`, have always a value for `Image.semanticsLabel`, check Theme color for contrast, etc. There is already ticket for having accessibility lints: 

The TypeScript world has already a accessibly linting package with these rules:

> [alt-text](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/alt-text.md): Enforce all elements that require alternative text have meaningful information to relay back to end user.
> [anchor-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/anchor-has-content.md): Enforce all anchors to contain accessible content.
> [anchor-is-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/anchor-is-valid.md): Enforce all anchors are valid, navigable elements.
> [aria-activedescendant-has-tabindex](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-activedescendant-has-tabindex.md): Enforce elements with aria-activedescendant are tabbable.
> [aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-props.md): Enforce all aria-* props are valid.
> [aria-proptypes](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-proptypes.md): Enforce ARIA state and property values are valid.
> [aria-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-role.md): Enforce that elements with ARIA roles must use a valid, non-abstract ARIA role.
> [aria-unsupported-elements](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/aria-unsupported-elements.md): Enforce that elements that do not support ARIA roles, states, and properties do not have those attributes.
> [autocomplete-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/autocomplete-valid.md): Enforce that autocomplete attributes are used correctly.
> [click-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/click-events-have-key-events.md): Enforce a clickable non-interactive element has at least one keyboard event listener.
> [heading-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/heading-has-content.md): Enforce heading (h1, h2, etc) elements contain accessible content.
> [html-has-lang](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/html-has-lang.md): Enforce <html> element has lang prop.
> [iframe-has-title](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/iframe-has-title.md): Enforce iframe elements have a title attribute.
> [img-redundant-alt](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/img-redundant-alt.md): Enforce <img> alt prop does not contain the word "image", "picture", or "photo".
> [interactive-supports-focus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/interactive-supports-focus.md): Enforce that elements with interactive handlers like onClick must be focusable.
> [label-has-associated-control](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md): Enforce that a label tag has a text label and an associated control.
> [lang](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/lang.md): Enforce lang attribute has a valid value.
> [media-has-caption](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/media-has-caption.md): Enforces that `<audio>` and `<video>` elements must have a `<track>` for captions.
> [mouse-events-have-key-events](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/mouse-events-have-key-events.md): Enforce that onMouseOver/onMouseOut are accompanied by onFocus/onBlur for keyboard-only users.
> [no-access-key](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-access-key.md): Enforce that the accessKey prop is not used on any element to avoid complications with keyboard commands used by a screenreader.
> [no-autofocus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-autofocus.md): Enforce autoFocus prop is not used.
> [no-distracting-elements](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-distracting-elements.md): Enforce distracting elements are not used.
> [no-interactive-element-to-noninteractive-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-interactive-element-to-noninteractive-role.md): Interactive elements should not be assigned non-interactive roles.
> [no-noninteractive-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-noninteractive-element-interactions.md): Non-interactive elements should not be assigned mouse or keyboard event listeners.
> [no-noninteractive-element-to-interactive-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-noninteractive-element-to-interactive-role.md): Non-interactive elements should not be assigned interactive roles.
> [no-noninteractive-tabindex](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-noninteractive-tabindex.md): tabIndex should only be declared on interactive elements.
> [no-onchange](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-onchange.md): Enforce usage of onBlur over onChange on select menus for accessibility.
> [no-redundant-roles](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-redundant-roles.md): Enforce explicit role property is not the same as implicit/default role property on element.
> [no-static-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/no-static-element-interactions.md): Enforce that non-interactive, visible elements (such as `<div>`) that have click handlers use the role attribute.
> [role-has-required-aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/role-has-required-aria-props.md): Enforce that elements with ARIA roles must have all required attributes for that role.
> [role-supports-aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/role-supports-aria-props.md): Enforce that elements with explicit or implicit roles defined contain only aria-* properties supported by that role.
> [scope](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/scope.md): Enforce scope prop is only used on `<th>` elements.
> [tabindex-no-positive](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/HEAD/docs/rules/tabindex-no-positive.md): Enforce tabIndex value is not greater than zero.

https://www.npmjs.com/package/eslint-plugin-jsx-a11y

---

So my suggestion would to leave this ticket open but focus on accessibly lints.

**Comment by sigurdm** [comment]
> There is already ticket for having accessibility lints: https://github.com/dart-lang/pub-dev/issues/2300

I think you linked to the wrong issue...

**Comment by nilsreichardt** [comment]
> I think you linked to the wrong issue...

Oh, yes - thanks for the catch! I fixed it :+1:

**Comment by sigurdm** [comment]
We still don't think this is the right issue-tracker. But hopefully we will find an owner for this at some point.
