### ISSUE TITLE
Broken Code Formatting On Home Page

### ISSUE THREAD

**Issue by victoreronmosele** [dart-lang/pub-dev#7493]
I just published a package and the formatting of the `Dart` code on the package's home is broken.

The formatting of the same code isn't broken on GitHub.

| pub.dev's homepage | github.com |
|---------|---------|
| ![badly formatted code sample on pub.dev's homepage](https://github.com/dart-lang/pub-dev/assets/19398044/64c99146-6e1b-427f-aaf8-f919272f6250) | ![well formatted code sample on github.com](https://github.com/dart-lang/pub-dev/assets/19398044/e2b3f21c-d40c-415c-9a0f-0893cee14692) |

Links:
- [pub.dev homepage](https://pub.dev/packages/web_color_picker/)
- [GitHub repository](https://github.com/victoreronmosele/flutter_web_color_picker)

Code: 
 
 ```dart
WebColorPicker(
  initialColor: textColor,
  onInput: (color, event) {
    setState(() {
      previewTextColor = color;
    });
  },
  onChange: (color, event) {
    setState(() {
      textColor = color;
    });
  },
  // ... other properties
),
```

**Comment by isoos** [comment]
Thanks for reporting! It looks like something swallows - at minimum - the spaces, I'll investigate what the core issue is.

**Comment by isoos** [comment]
This is a `package:markdown` bug that seems to have been fixed in `7.2.1` (we are on `7.2.0`). We will upgrade to the newer version and the rendering issue should be fixed.

**Comment by victoreronmosele** [comment]
Thanks @isoos for the quick action!

I still see the bug on the home page, though even after republishing the package. 

Do I need to wait for some time to see the fix?

**Comment by isoos** [comment]
> I still see the bug on the home page, though, even after republishing the package.

You don't need to republish the package. The site will get updated automatically once we deploy this change (not sure when then next deployment will be).

**Comment by victoreronmosele** [comment]
Okay, thanks!
